name: Deploy 03-final-development-pipeline-integration to Render

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
        working-directory: 03-final-development-pipeline-integration

      # Step 4: Run pytest
      - name: Run tests with pytest
        run: |
          pytest
        continue-on-error: false
        working-directory: 03-final-development-pipeline-integration

      # Step 5: Run flake8
      - name: Run flake8 for code style checks
        run: |
          flake8 .
        continue-on-error: false
        working-directory: 03-final-development-pipeline-integration

      # Step 6: Trigger Render Deploy Hook (if tests and linting pass)
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}